// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineExaminationSystem.Entities;

public partial class Department
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? MgrId { get; set; }

    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    public virtual Instructor Mgr { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}