// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineExaminationSystem.Entities;

public partial class Exam
{
    public int Id { get; set; }

    public DateOnly Date { get; set; }

    public int InsId { get; set; }

    public int CId { get; set; }

    public int? Duration { get; set; }

    public virtual Course CIdNavigation { get; set; }

    public virtual Instructor Ins { get; set; }

    public virtual ICollection<StudentExam> StudentExams { get; set; } = new List<StudentExam>();

    public virtual ICollection<Question> QIds { get; set; } = new List<Question>();
}