// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineExaminationSystem.Entities;

public partial class Instructor : Person
{
    //public int Id { get; set; }

    public int DeptId { get; set; }

    public double? Salary { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual Department Dept { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    //public virtual Person IdNavigation { get; set; }

    public virtual ICollection<Course> CIds { get; set; } = new List<Course>();
}