// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineExaminationSystem.Entities;

public partial class Person
{
    public int Id { get; set; }

    public string Fname { get; set; }

    public string Lname { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string AccountState { get; set; }

    //public virtual Instructor Instructor { get; set; }

    //public virtual Student Student { get; set; }
}