// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineExaminationSystem.Entities;

public partial class QuestionAnswer
{
    public int Id { get; set; }

    public string AnswerText { get; set; }

    public int ModelAnswer { get; set; }

    public int QId { get; set; }

    public virtual Question QIdNavigation { get; set; }

    public virtual ICollection<StudentAnswerQuestion> StudentAnswerQuestions { get; set; } = new List<StudentAnswerQuestion>();
}