// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineExaminationSystem.Entities;

public partial class Question
{
    public int Id { get; set; }

    public string QuestionText { get; set; }

    public int Mark { get; set; }

    public string Type { get; set; }

    public string Complexity { get; set; }

    public int? CId { get; set; }

    public virtual Course CIdNavigation { get; set; }

    public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; } = new List<QuestionAnswer>();

    public virtual ICollection<StudentAnswerQuestion> StudentAnswerQuestions { get; set; } = new List<StudentAnswerQuestion>();

    public virtual ICollection<Exam> EIds { get; set; } = new List<Exam>();
}