// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineExaminationSystem.Entities;

public partial class StudentAnswerQuestion
{
    public int StId { get; set; }

    public int QId { get; set; }

    public int QansId { get; set; }

    public int? Grade { get; set; }

    public virtual Question QIdNavigation { get; set; }

    public virtual QuestionAnswer Qans { get; set; }

    public virtual Student St { get; set; }
}