// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineExaminationSystem.Entities;

public partial class StudentExam
{
    public int StId { get; set; }

    public int EId { get; set; }

    public int? ExamGrade { get; set; }

    public int? IsTaken { get; set; }

    public virtual Exam EIdNavigation { get; set; }

    public virtual Student St { get; set; }
}