// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineExaminationSystem.Entities;

public partial class Topic
{
    public int TId { get; set; }

    public int CId { get; set; }

    public string Name { get; set; }

    public virtual Course CIdNavigation { get; set; }
}